### ISSUE TITLE
Exposing Testkube with Contour makes OAuth not work correctly.

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2176] opened 2022-08-29 14:06 UTC
**Describe the bug**

**Comment by ili-shmidt-wib** [comment] 2022-08-30 21:01
Hi @ypoplavs,
The issue is that even though we configure our testkube according to the testkube OAuth docs, when requesting testkube dashboard, we are not redirected to the OAuth page.

**Comment by ypoplavs** [comment] 2022-09-26 07:17
Hello @ili-shmidt-wib ,

It looks like Oauth2 integration is not supported by Contour yet. Please see the Github issue for that: https://github.com/projectcontour/contour/issues/2664

As per their official documentation, it’s possible to enable simple authorisation by using server named [contour-authserver](https://github.com/projectcontour/contour-authserver): https://projectcontour.io/guides/external-authorization/

**Comment by vsukhin** [comment] 2022-09-27 15:48
closing for now

**Closed by vsukhin** 2022-09-27 15:48 UTC
Labels: bug 🐛
