### ISSUE TITLE
API-Pod crashes after viewing test artefacts

### ISSUE THREAD

**Issue by aachermann** [kubeshop/testkube#3414] opened 2023-03-15 10:28 UTC
**Describe the bug**
viewing artefacts on dashboard doesn't work. We have configured external S3. After clicking the "Artefact"-Tab in a Execution-Run the API-Pod crashes. (The log output is under additional context)
the test-executor can upload the artefacts to the external Minio, so there are some files in the bucket.

**To Reproduce**
1. Run a Test and write artefacts to external S3-destination (minio)
2. Specify '...'
3. See error

**Expected behavior**
Api-Pod crashes and throw "panic: runtime error: invalid memory address or nil pointer dereference"

**Version / Cluster**
- Which testkube version? latest
- What Kubernetes cluster? OpenShift
- What Kubernetes version? 4.11.28

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
![Screenshot 2023-03-15 111728](https://user-images.githubusercontent.com/119501315/225280467-c3165375-b072-449d-8265-a3edaf696f99.png)

![image](https://user-images.githubusercontent.com/119501315/225281686-c96cef18-1155-4a8a-894e-0caf6d7e8960.png)

**Additional context**
LOG-Output: 
[log.txt](https://github.com/kubeshop/testkube/files/10978578/log.txt)

// API-Container Config
containers:
        - name: testkube-api
          env:
            - name: APISERVER_PORT
              value: "8088"
            - name: API_MONGO_DSN
              value: "mongodb://testkube-mongodb:27017"
            - name: API_MONGO_ALLOW_DISK_USE
              value: "true"
            - name: NATS_URI
              value: nats://testkube-nats:4222
            - name: POSTMANEXECUTOR_URI
              value: ""
            - name: TESTKUBE_ANALYTICS_ENABLED
              value: "false"
            - name: SLACK_TOKEN
              value: ""
            - name: "STORAGE_ENDPOINT"
              value:  "abc.xyz.ch:80"
            - name: "STORAGE_BUCKET"
              value:  "test-curl-test"
            - name: "STORAGE_ACCESSKEYID"
              value:  "xxx"
            - name: "STORAGE_SECRETACCESSKEY"
              value: "xxx"
            - name: "STORAGE_LOCATION"
              value: ""
            - name: "STORAGE_TOKEN"
              value: ""
            - name: "STORAGE_SSL"
              value:  "false"
            - name: "SCRAPPERENABLED"
              value:  "true"
            - name: "LOGS_BUCKET"
              value:  "testkube-logs"
            - name: "LOGS_STORAGE"
              value:  "mongo"
            - name: TESTKUBE_NAMESPACE
              value: "x-testkube-test"
            - name: JOB_SERVICE_ACCOUNT_NAME
              value: ""
            - name: APISERVER_FULLNAME
              value: "testkube-api-server"
            - name: APISERVER_CONFIG
              value: "testkube-api-server-config-x-testkube-test"
            - name: TESTKUBE_OAUTH_CLIENTID
              value:  ""
            - name: TESTKUBE_OAUTH_CLIENTSECRET
              value:  ""
            - name: TESTKUBE_OAUTH_PROVIDER
              value:  "github"
            - name: TESTKUBE_OAUTH_SCOPES
              value:  ""
            - name: TESTKUBE_CLOUD_URL
              value:  "agent.testkube.io:443"
            - name: TESTKUBE_CONFIG_DIR
              value: /app/config
          image: docker.io/kubeshop/testkube-api-server:1.9.33

**Comment by vsukhin** [comment] 2023-03-15 11:20
hey @aachermann thank you for such a detailed report. sounds like minio connection is really broken. Do you see anything in minio pod logs?

**Comment by aachermann** [comment] 2023-03-15 13:50
hi @vsukhin 
we are running minio in a enterprise-environment (no Pods on Kubernetes) and consume it as a service. 
however, I was able to make a trace:
[s3_trace_15032023.txt](https://github.com/kubeshop/testkube/files/10980458/s3_trace_15032023.txt)
in the trace you see, that the last call was the PUT-method which succeeded. When I redirect to the Artifact-Tab, there was no traffic to our Minio. So I believe, there is a bug in the application.

**Comment by vsukhin** [comment] 2023-03-15 15:14
Thank you, will try to reproduce

**Comment by vsukhin** [comment] 2023-03-21 17:48
hey @aachermann yes, we know,where the problem happens, butt we're short of hands to fix it right now. it's in our to do list

**Comment by TheBrunoLopes** [comment] 2023-03-28 09:53
this issue may be related with the changes we did for the cloud ? cc: @dejanzele

**Comment by vsukhin** [comment] 2023-04-10 09:34
should be fixed by @dejanzele in latest release

**Closed by vsukhin** 2023-04-10 09:34 UTC
Labels: bug 🐛

**Comment by Moser-ss** [comment] 2023-04-10 12:31
Hey,  looks like the version v1.10.41 re introduce this issue. I am having the same error in the testkube-api server when trying to see artifacts.
Reverting to version v1.10.40 solve the issue

**Comment by vsukhin** [comment] 2023-04-10 12:34
hey @dejanzele can you please check it?
