### ISSUE TITLE
Dashboard - execution drawer - lag while opening for bigger log outputs

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3627] opened 2023-04-06 10:40 UTC
There is a significant lag when opening the execution drawer. Whole execution logs are downloaded before the drawer is opened, which can take a few, or even several dozen seconds depending on the log size and internet connection.
https://user-images.githubusercontent.com/1473096/230352662-09ba6c26-b506-4c21-949a-5c89dc8a9c3f.mp4

Example test: https://demo.testkube.io/tests/executions/large-logs-11mb-test (11MB of log output)

**Suggested improvement**
Not predownloading the whole logs? Opening drawer, and showing loading animation on logs? Maybe just logs tail (and dynamic loading)?

**Comment by rangoo94** [comment] 2023-04-06 10:46
The problem is with displaying 11MB of logs. As a solution, we could consider:
* show the last 300 lines of logs and add a button/link "show all logs", or
* prepare our own component for logs that would lazily load the text

I would rather suggest the 1st option - it would be easier and should solve the problem.

**Comment by fivenp** [comment] 2023-04-06 10:51
i‘d think a short term fix is to load last 300 lines initially and have a button to load „1000 more lines“ (instead of load all) until there‘s nothing more to load… 

in the end i guess we‘ll have to do bidirectional lazy loading and load/unload dynamically based on the current cursor - because we dont want to have 11mb loaded on the DOM at any time? :)

**Comment by rangoo94** [comment] 2023-04-06 11:29
After checking, there is also a log downloaded - but for that, I believe the solution with a loader will be the best.

**Comment by rangoo94** [comment] 2023-04-11 12:46
Should be fixed with the existing PRs:

* Execution Details now have a loader indicating that the data has been requested
* Logs are cut to show only 300 lines and you may show full output when going to top

**Closed by rangoo94** 2023-04-11 12:46 UTC
Labels: service:dashboard 🎡
