### ISSUE TITLE
[bug] Model loses form date if user clicks outside

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2841] opened 2022-12-03 23:15 UTC
- Disable exiting the modal when clicking outside:
https://user-images.githubusercontent.com/13501228/205465964-0f985465-7571-4069-9176-708839477fe4.mov

**Comment by tkonieczny** [comment] 2022-12-06 13:39
duplicate of #2327

**Closed** 2022-12-06 21:16 UTC
Labels: bug 🐛
