### ISSUE TITLE
Direct kubectl access

### ISSUE THREAD

**Issue by bioslikk** [kubeshop/testkube#759] opened 2022-01-12 10:38 UTC
**Description**
For some of Testkube command calls, it seems that I require that **Kube-server api is exposed** and my **user has the necessary permissions**. However, for some environments like production, users wouldn't necessarily have access to that. As a user, it shouldn't be necessary to have those permissions to run the tests.

**Suggestion** 
![Testkube_CLI_FLOW](https://user-images.githubusercontent.com/13501228/149124539-7374c8a2-3b7e-4ca1-97ed-cab457c6646a.jpg)
Would something like this work ?

**Comment by exu** [comment] 2022-01-14 11:28
Duplicate of #233

**Closed by exu** 2022-01-14 11:28 UTC
Labels: enhancement, discussion 🗣️
