### ISSUE TITLE
Envs are not passed to the executor container

### ISSUE THREAD

**Issue by nicufk** [kubeshop/testkube#2485] opened 2022-10-06 21:09 UTC
**Describe the bug**

**To Reproduce**

Having a test with this execution request
```
  executionRequest:
    envs:
      MY_ENV: bla
      SECOND: two
```

does not pass them to the executor container

```
    Environment:
      DEBUG:                   
      RUNNER_ENDPOINT:         testkube-minio-service-testkube:9000
      RUNNER_ACCESSKEYID:      ***
      RUNNER_SECRETACCESSKEY:  ***
      RUNNER_LOCATION:         
      RUNNER_TOKEN:            
      RUNNER_SSL:              false
      RUNNER_SCRAPPERENABLED:  true
      RUNNER_DATADIR:          /data
    Mounts:
      /data from data-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-t945n (ro)
```

**Comment by shanesavoie** [comment] 2022-10-06 21:19
FYI, there seems to be the same issue with both `envs` and `variables`.

**Comment by shanesavoie** [comment] 2022-10-07 19:31
@povilasv envs are confirmed working for me. Thanks for looking at variables!

**Comment by TheLeanMachine** [comment] 2022-10-10 11:44
Hey @povilasv ,

its does not seem to work with the "container executor", at least.

I created the test with...
```
kubectl testkube create test --name nx-xchange-frontend-v26 --type nx-xchange-frontend/test --executor-args '--version' --git-branch master --git-uri https://bitbucket.org/xchangeteam/xchange-frontend.git --git-username kai_hoelscher --git-token ATBBxFyBuXbVnbXrDyCpP69Ap6kqC368C57B --env RUNNER_DIR=/foobar
```

Which gives me this test definition...
![Screenshot 2022-10-10 at 13 41 54](https://user-images.githubusercontent.com/3470837/194858521-a36dc611-1656-4555-9a2d-921ed1797a98.png)

But when I run this executor command...
![Screenshot 2022-10-10 at 13 43 25](https://user-images.githubusercontent.com/3470837/194858736-fd5e9fdc-16b2-49fe-aadb-f3ba6cb9cba0.png)

I see this output...
![Screenshot 2022-10-10 at 13 44 04](https://user-images.githubusercontent.com/3470837/194858842-18e0a26a-edb5-4f6f-a3e2-5be20dbf082a.png)

My versions...
<img width="511" alt="Screenshot 2022-10-10 at 13 38 04" src="https://user-images.githubusercontent.com/3470837/194858309-af66b656-0af8-43e1-938b-864932d9ae6c.png">

**Comment by vsukhin** [comment] 2022-10-10 14:02
And these test results
```
 kubectl testkube get execution 6344227a6418b3b665aa7584
ID:         6344227a6418b3b665aa7584
Name        frontend-test-7
Number:            7
Test name:         frontend-test
Type:              frontend/test
Status:            passed
Start time:        2022-10-10 13:47:38.373 +0000 UTC
End time:          2022-10-10 13:47:55.14 +0000 UTC
Duration:          00:00:16

{"type":"event","content":"running test [6344227a6418b3b665aa7584]"}
{"type":"line","content":"created content path: /data/repo/"}
{"type":"result","result":{"status":"running"}}
/app
Navigate to checked-out repository located in /data/repo
Installing NPM-dependencies...
Who am I? - 
node
total 28K
drwxrwxrwx 7 root root 4.0K Oct 10 13:47 .
drwxrwxrwx 3 root root 4.0K Oct 10 13:47 ..
drwxrwxrwx 8 root root 4.0K Oct 10 13:47 .git
drwxrwxrwx 5 root root 4.0K Oct 10 13:47 cypress
drwxrwxrwx 3 root root 4.0K Oct 10 13:47 params-test
drwxrwxrwx 4 root root 4.0K Oct 10 13:47 v10-e2e
drwxrwxrwx 4 root root 4.0K Oct 10 13:47 v8-test
Checkout dir - 
cypress
total 148K
drwxrwxrwx 5 root root 4.0K Oct 10 13:47 .
drwxrwxrwx 7 root root 4.0K Oct 10 13:47 ..
-rwxrwxrwx 1 root root   13 Oct 10 13:47 .gitignore
-rwxrwxrwx 1 root root   59 Oct 10 13:47 README.md
drwxrwxrwx 6 root root 4.0K Oct 10 13:47 cypress
-rwxrwxrwx 1 root root    3 Oct 10 13:47 cypress.json
-rwxrwxrwx 1 root root 109K Oct 10 13:47 package-lock.json
-rwxrwxrwx 1 root root   55 Oct 10 13:47 package.json
drwxrwxrwx 2 root root 4.0K Oct 10 13:47 plugins
drwxrwxrwx 2 root root 4.0K Oct 10 13:47 support

Status Test execution completed with success 🥇

```

**Comment by vsukhin** [comment] 2022-10-11 06:59
Closing, support was implemented, feel free to reopen, if you still have issues

**Closed by vsukhin** 2022-10-11 06:59 UTC
Labels: bug 🐛

**Comment by TheLeanMachine** [comment] 2022-10-11 09:21
Thanks @vsukhin for your efforts!

Cannot explain this. Maybe I will simply try it again...

**Comment by TheLeanMachine** [comment] 2022-10-11 11:11
@vsukhin ...just for sakes of completeness: I used the CRD from above + created the test, just like you.

Yeah, seems I have done sth. wrong, _as I get the same result, now..._
![Screenshot 2022-10-11 at 13 10 21](https://user-images.githubusercontent.com/3470837/195075322-00f2ef37-2f88-4c04-bbc8-55ecf5307f4a.png)
