### ISSUE TITLE
`kubeshop/testkube-run-action` (GH) - `Connection lost, reconnecting...`

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4997] opened 2024-02-12 12:05 UTC
**Describe the bug**
`Connection lost, reconnecting...` is displayed frequently (every few seconds, or even multiple times a second based on user feedback) resulting in massive logs while running tests with `kubeshop/testkube-run-action` actions.

example:
https://github.com/kubeshop/testkube-dashboard/actions/runs/7815479231/job/21318944175?pr=1012

user report: https://testkubeworkspace.slack.com/archives/C06D9EYTQ2J/p1707637576255869

**Comment by rangoo94** [comment] 2024-02-16 09:00
@tkonieczny, I deleted the `kubeshop/setup-testkube` from the equation, as I don't think there is any problem in there. Have you experienced any?

In regards of `kubeshop/testkube-run-action', I found the issue - basically, after the execution is finished, we close the WebSocket connection from BE, but the Execution endpoint is still not marked as done in the database, so we try to fetch them again. I'll check for some workaround there.

**Comment by rangoo94** [comment] 2024-02-16 09:16
To sum up:

The problem is happening after the Test finishes:
1. The container is finished, so the server is closing the connection for the logs
2. The GitHub Action fetches current execution status, but it's still running in the database
3. Because of Logs V2, on reconnection now we receive all the logs, so we display them
   1. In Logs V1, we display the last few lines again
5. The server again closes the connection as the container is closed
6. We do again steps 2-4, until the Execution status is updated in the database

We've got few solutions there:
1. **GH:** Do not show the logs that have been displayed before (but: it's not fully compatible with Logs V1 in case of duplicated lines, and still there will be `Connection lost, reconnecting...` message, just without duplicated logs)
2. Same as 1st, but we won't show `Connection lost, reconnecting...` message
3. **BE:** Do not close WebSocket connection, until the execution is marked as finished in the database (at the moment we depend on the K8S container only; quite hackish, but may make sense)
4. **BE:** Set the Execution status earlier in the database (may be complex, especially considering separate artifacts job)
I would say that the 2nd option is viable, although I guess that it will have some edge cases anyway too. 
[@Vladislav Sukhin](https://kubeshop.slack.com/team/U023FUPD3DY)
, what do you think about it? (edited) 





Dawid Rusnak
  [< 1 minute ago](https://kubeshop.slack.com/archives/C052ULB3T0F/p1708074855235619?thread_ts=1708018738.544659&cid=C052ULB3T0F)
Alternatively, the 1st solution + not displaying the Connection lost, reconnecting... message, in case the server has closed the connection (pros: less verbose, cons: less verbose :slightly_smiling_face:)

**Comment by vsukhin** [comment] 2024-02-21 16:28
Can we do #5 then?

**Comment by rangoo94** [comment] 2024-02-22 08:38
Sure thing 👍 @haneabogdan, @devcatalin, @topliceanurazvan - do you maybe have some time to do that? It's basically adding a timeout before reconnecting on `close` event

**Comment by devcatalin** [comment] 2024-03-01 11:22
I've added the tiemout before reconnecting on the close event.
After that, the repo has been archived since we're deprecating in favor of the setup-testkube github action.
Migration shouldn't be difficult and there is some information about it here: https://docs.testkube.io/articles/run-tests-with-github-actions

**Closed by devcatalin** 2024-03-01 11:22 UTC
Labels: bug 🐛
